version: '3'

services:

  backend:
    build: backend
    ports:
      - 8000:8000

  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend

  database:
    build: database
    depends_on:
      - backend
    ports:
      - 8080:8080
    